name: Newfound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7430991975124925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ad9c80'
    - '#3a3743'
    - '#d6d5db'
    - '#20130f'
    - '#a2756b'
  brandStrength: 0.6888213669881225
  lightness: 0.8735484122298658
  saturation: 0.29997146502137184
  rhythmicContrast: 0.36285603139549494
purpose: []
